/**
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl;

import edu.ustb.sei.mde.bxcore.dsl.BXCoreStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class BXCoreStandaloneSetup extends BXCoreStandaloneSetupGenerated {
  public static void doSetup() {
    new BXCoreStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
