/**
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl.ui;

import edu.ustb.sei.mde.bxcore.dsl.ui.AbstractBXCoreUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class BXCoreUiModule extends AbstractBXCoreUiModule {
  public BXCoreUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
