/**
 * generated by Xtext 2.10.0
 */
package edu.ustb.sei.mde.xmuxtext.validation;

import com.google.common.base.Objects;
import edu.ustb.sei.mde.xmu2.ArithmeticRule;
import edu.ustb.sei.mde.xmu2.ModelRule;
import edu.ustb.sei.mde.xmu2.Parameter;
import edu.ustb.sei.mde.xmu2.VariableDeclaration;
import edu.ustb.sei.mde.xmu2.Xmu2Package;
import edu.ustb.sei.mde.xmu2.expression.Expression;
import edu.ustb.sei.mde.xmu2.expression.ExpressionPackage;
import edu.ustb.sei.mde.xmu2.expression.LoopPath;
import edu.ustb.sei.mde.xmu2.expression.VariableExpression;
import edu.ustb.sei.mde.xmu2.pattern.Pattern;
import edu.ustb.sei.mde.xmu2.pattern.PatternNode;
import edu.ustb.sei.mde.xmu2.statement.AssignStatement;
import edu.ustb.sei.mde.xmu2.statement.CaseClause;
import edu.ustb.sei.mde.xmu2.statement.DeleteLinkStatement;
import edu.ustb.sei.mde.xmu2.statement.DeleteNodeStatement;
import edu.ustb.sei.mde.xmu2.statement.EnforcePatternStatement;
import edu.ustb.sei.mde.xmu2.statement.ExpressionCaseClause;
import edu.ustb.sei.mde.xmu2.statement.Fail;
import edu.ustb.sei.mde.xmu2.statement.ForEachStatement;
import edu.ustb.sei.mde.xmu2.statement.PatternCaseClause;
import edu.ustb.sei.mde.xmu2.statement.Statement;
import edu.ustb.sei.mde.xmu2.statement.StatementPackage;
import edu.ustb.sei.mde.xmu2.statement.SwitchStatement;
import edu.ustb.sei.mde.xmu2.statement.UpdateClause;
import edu.ustb.sei.mde.xmu2.statement.UpdateStatement;
import edu.ustb.sei.mde.xmu2.util.AnalysisUtil;
import edu.ustb.sei.mde.xmu2.util.Constants;
import edu.ustb.sei.mde.xmu2common.DomainTag;
import edu.ustb.sei.mde.xmuxtext.customize.common.ModelIterator;
import edu.ustb.sei.mde.xmuxtext.validation.Xmu2Validator;
import java.util.HashSet;
import java.util.Set;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.xbase.lib.Exceptions;

@SuppressWarnings("all")
public class VariableValidityContext {
  private Set<String> sourceVariableNames = new HashSet<String>();
  
  private Set<String> viewVariableNames = new HashSet<String>();
  
  private Set<String> updatedSourceVariableNames = new HashSet<String>();
  
  private Set<String> normalVariableNames = new HashSet<String>();
  
  public void addSourceVariableName(final String n) {
    String _nonUpdatedSourceVariableName = AnalysisUtil.getNonUpdatedSourceVariableName(n);
    this.sourceVariableNames.add(_nonUpdatedSourceVariableName);
    String _updatedSourceVariableName = AnalysisUtil.getUpdatedSourceVariableName(n);
    this.updatedSourceVariableNames.add(_updatedSourceVariableName);
  }
  
  public void addViewVariableName(final String n) {
    this.viewVariableNames.add(n);
  }
  
  public void addUpdatedSourceVariableName(final String n) {
    String _nonUpdatedSourceVariableName = AnalysisUtil.getNonUpdatedSourceVariableName(n);
    this.sourceVariableNames.add(_nonUpdatedSourceVariableName);
    String _updatedSourceVariableName = AnalysisUtil.getUpdatedSourceVariableName(n);
    this.updatedSourceVariableNames.add(_updatedSourceVariableName);
  }
  
  public void addNormalVariableName(final String n) {
    this.normalVariableNames.add(n);
  }
  
  public boolean existInSourceVariable(final String n) {
    return this.sourceVariableNames.contains(n);
  }
  
  public boolean existInViewVariable(final String n) {
    return this.viewVariableNames.contains(n);
  }
  
  public boolean existInUpdatedSourceVariable(final String n) {
    return this.updatedSourceVariableNames.contains(n);
  }
  
  public boolean existInNormalVariable(final String n) {
    return this.normalVariableNames.contains(n);
  }
  
  public boolean isValidNonUpdatedVariableName(final String n) {
    boolean _endsWith = n.endsWith(Constants.POST);
    return (!_endsWith);
  }
  
  public boolean isDuplicateNormalVariable(final String name) {
    return ((this.existInNormalVariable(name) || 
      this.existInSourceVariable(name)) || 
      this.existInViewVariable(name));
  }
  
  public boolean isDuplicateSourceVariable(final String name) {
    return (this.existInNormalVariable(name) || 
      this.existInViewVariable(name));
  }
  
  public boolean isDuplicateViewVariable(final String name) {
    return (this.existInNormalVariable(name) || 
      this.existInSourceVariable(name));
  }
  
  public boolean isDuplicateUpdatedSourceVariable(final String name) {
    String converted_name = AnalysisUtil.getNonUpdatedSourceVariableName(name);
    return (this.existInNormalVariable(converted_name) || 
      this.existInViewVariable(converted_name));
  }
  
  public void collectVariablesInPattern(final Pattern source, final DomainTag domain, final Xmu2Validator resource) {
    TreeIterator<EObject> sp = source.eAllContents();
    while (sp.hasNext()) {
      {
        EObject o = sp.next();
        if ((o instanceof VariableDeclaration)) {
          EObject _eContainer = ((VariableDeclaration)o).eContainer();
          if ((_eContainer instanceof LoopPath)) {
          } else {
            String varName = ((VariableDeclaration) o).getName();
            boolean _equals = Objects.equal(domain, DomainTag.SOURCE);
            if (_equals) {
              boolean _isValidNonUpdatedSourceVariableName = AnalysisUtil.isValidNonUpdatedSourceVariableName(varName);
              boolean _equals_1 = (_isValidNonUpdatedSourceVariableName == false);
              if (_equals_1) {
                EObject _eContainer_1 = ((VariableDeclaration)o).eContainer();
                EReference _eContainmentFeature = ((VariableDeclaration)o).eContainmentFeature();
                resource.addError("the name of a source variable should not end with \'@post\'", _eContainer_1, _eContainmentFeature);
              }
              boolean _isDuplicateSourceVariable = this.isDuplicateSourceVariable(varName);
              if (_isDuplicateSourceVariable) {
                EObject _eContainer_2 = ((VariableDeclaration)o).eContainer();
                EReference _eContainmentFeature_1 = ((VariableDeclaration)o).eContainmentFeature();
                resource.addError("the source variable has been declared in a conflict context", _eContainer_2, _eContainmentFeature_1);
              } else {
                this.addSourceVariableName(varName);
              }
            } else {
              boolean _equals_2 = Objects.equal(domain, DomainTag.VIEW);
              if (_equals_2) {
                boolean _isValidNonUpdatedSourceVariableName_1 = AnalysisUtil.isValidNonUpdatedSourceVariableName(varName);
                boolean _equals_3 = (_isValidNonUpdatedSourceVariableName_1 == false);
                if (_equals_3) {
                  EObject _eContainer_3 = ((VariableDeclaration)o).eContainer();
                  EReference _eContainmentFeature_2 = ((VariableDeclaration)o).eContainmentFeature();
                  resource.addError("the name of a view variable should not end with \'@post\'", _eContainer_3, _eContainmentFeature_2);
                }
                boolean _isDuplicateViewVariable = this.isDuplicateViewVariable(varName);
                if (_isDuplicateViewVariable) {
                  EObject _eContainer_4 = ((VariableDeclaration)o).eContainer();
                  EReference _eContainmentFeature_3 = ((VariableDeclaration)o).eContainmentFeature();
                  resource.addError("the view variable has been declared in a conflict context", _eContainer_4, _eContainmentFeature_3);
                } else {
                  this.addViewVariableName(varName);
                }
              } else {
                boolean _equals_4 = Objects.equal(domain, DomainTag.UPDATED_SOURCE);
                if (_equals_4) {
                  boolean _isDuplicateUpdatedSourceVariable = this.isDuplicateUpdatedSourceVariable(varName);
                  if (_isDuplicateUpdatedSourceVariable) {
                    EObject _eContainer_5 = ((VariableDeclaration)o).eContainer();
                    EReference _eContainmentFeature_4 = ((VariableDeclaration)o).eContainmentFeature();
                    resource.addError("the updated source variable has been declared in a conflict context", _eContainer_5, _eContainmentFeature_4);
                  } else {
                    this.addSourceVariableName(varName);
                  }
                } else {
                  boolean _equals_5 = Objects.equal(domain, DomainTag.NORMAL);
                  if (_equals_5) {
                    boolean _isValidNonUpdatedSourceVariableName_2 = AnalysisUtil.isValidNonUpdatedSourceVariableName(varName);
                    boolean _equals_6 = (_isValidNonUpdatedSourceVariableName_2 == false);
                    if (_equals_6) {
                      EObject _eContainer_6 = ((VariableDeclaration)o).eContainer();
                      EReference _eContainmentFeature_5 = ((VariableDeclaration)o).eContainmentFeature();
                      resource.addError("the name of a normal variable should not end with \'@post\'", _eContainer_6, _eContainmentFeature_5);
                    }
                    if ((this.existInSourceVariable(varName) || this.existInViewVariable(varName))) {
                      EObject _eContainer_7 = ((VariableDeclaration)o).eContainer();
                      EReference _eContainmentFeature_6 = ((VariableDeclaration)o).eContainmentFeature();
                      resource.addError("the normal variable has been declared in a conflict context", _eContainer_7, _eContainmentFeature_6);
                    } else {
                      this.addUpdatedSourceVariableName(varName);
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
  
  public void checkVariableUsage(final EObject root, final Xmu2Validator res, final DomainTag context) {
    try {
      ModelIterator it = new ModelIterator(root);
      while (it.hasNext()) {
        {
          EObject o = it.next();
          if ((o instanceof VariableExpression)) {
            String name = ((VariableExpression) o).getVariable();
            boolean _isIteratorName = this.isIteratorName(name, o);
            if (_isIteratorName) {
            } else {
              boolean _equals = Objects.equal(context, DomainTag.NORMAL);
              if (_equals) {
                if (((this.existInNormalVariable(name) || 
                  this.existInSourceVariable(name)) || 
                  this.existInViewVariable(name))) {
                } else {
                  res.addError("undefined normal variable", o, ExpressionPackage.Literals.VARIABLE_EXPRESSION__VARIABLE);
                }
              } else {
                boolean _equals_1 = Objects.equal(context, DomainTag.SOURCE);
                if (_equals_1) {
                  if ((this.existInNormalVariable(name) || 
                    this.existInSourceVariable(name))) {
                  } else {
                    res.addError("undefined source variable", o, ExpressionPackage.Literals.VARIABLE_EXPRESSION__VARIABLE);
                  }
                } else {
                  boolean _equals_2 = Objects.equal(context, DomainTag.VIEW);
                  if (_equals_2) {
                    if ((this.existInNormalVariable(name) || 
                      this.existInViewVariable(name))) {
                    } else {
                      res.addError("undefined view variable", o, ExpressionPackage.Literals.VARIABLE_EXPRESSION__VARIABLE);
                    }
                  } else {
                    boolean _equals_3 = Objects.equal(context, DomainTag.UPDATED_SOURCE);
                    if (_equals_3) {
                      if (((this.existInNormalVariable(name) || 
                        this.existInSourceVariable(name)) || 
                        this.existInUpdatedSourceVariable(name))) {
                      } else {
                        boolean _existInViewVariable = this.existInViewVariable(name);
                        if (_existInViewVariable) {
                          res.addWarning("using view variable in the context of updated source is not recommended", o, ExpressionPackage.Literals.VARIABLE_EXPRESSION__VARIABLE);
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    } catch (final Throwable _t) {
      if (_t instanceof Exception) {
        final Exception e = (Exception)_t;
        EObject _eContainer = root.eContainer();
        EReference _eContainmentFeature = root.eContainmentFeature();
        res.addWarning("validity check is not finished because of some exceptions", _eContainer, _eContainmentFeature);
      } else {
        throw Exceptions.sneakyThrow(_t);
      }
    }
  }
  
  public boolean isIteratorName(final String name, final EObject root) {
    EClass _loopPath = ExpressionPackage.eINSTANCE.getLoopPath();
    EObject _ancestor = AnalysisUtil.getAncestor(root, _loopPath);
    LoopPath loop = ((LoopPath) _ancestor);
    boolean _equals = Objects.equal(loop, null);
    if (_equals) {
      return false;
    } else {
      VariableDeclaration _variable = loop.getVariable();
      String _name = _variable.getName();
      boolean _equals_1 = _name.equals(name);
      if (_equals_1) {
        return true;
      } else {
        EObject _eContainer = loop.eContainer();
        return this.isIteratorName(name, _eContainer);
      }
    }
  }
  
  public void collectVariableNames(final EObject root, final Xmu2Validator resource) {
    try {
      if ((root instanceof ModelRule)) {
        EList<Parameter> _parameters = ((ModelRule) root).getParameters();
        for (final Parameter p : _parameters) {
          DomainTag _tag = ((Parameter) p).getTag();
          boolean _equals = Objects.equal(_tag, DomainTag.NORMAL);
          if (_equals) {
            String _name = p.getName();
            boolean _isValidNonUpdatedSourceVariableName = AnalysisUtil.isValidNonUpdatedSourceVariableName(_name);
            boolean _equals_1 = (_isValidNonUpdatedSourceVariableName == false);
            if (_equals_1) {
              resource.addError("the name of a normal variable should not end with \'@post\'", p, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
            }
            String _name_1 = p.getName();
            boolean _isDuplicateNormalVariable = this.isDuplicateNormalVariable(_name_1);
            if (_isDuplicateNormalVariable) {
              resource.addError("the normal variable has been declared in a conflict context", p, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
            } else {
              String _name_2 = ((Parameter) p).getName();
              this.addNormalVariableName(_name_2);
            }
          } else {
            DomainTag _tag_1 = ((Parameter) p).getTag();
            boolean _equals_2 = Objects.equal(_tag_1, DomainTag.SOURCE);
            if (_equals_2) {
              String _name_3 = p.getName();
              boolean _isValidNonUpdatedSourceVariableName_1 = AnalysisUtil.isValidNonUpdatedSourceVariableName(_name_3);
              boolean _equals_3 = (_isValidNonUpdatedSourceVariableName_1 == false);
              if (_equals_3) {
                resource.addError("the name of a source variable should not end with \'@post\'", p, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
              }
              String _name_4 = p.getName();
              boolean _isDuplicateSourceVariable = this.isDuplicateSourceVariable(_name_4);
              if (_isDuplicateSourceVariable) {
                resource.addError("the source variable has been declared in a conflict context", p, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
              } else {
                String _name_5 = ((Parameter) p).getName();
                this.addSourceVariableName(_name_5);
              }
            } else {
              DomainTag _tag_2 = ((Parameter) p).getTag();
              boolean _equals_4 = Objects.equal(_tag_2, DomainTag.VIEW);
              if (_equals_4) {
                String _name_6 = p.getName();
                boolean _isValidNonUpdatedSourceVariableName_2 = AnalysisUtil.isValidNonUpdatedSourceVariableName(_name_6);
                boolean _equals_5 = (_isValidNonUpdatedSourceVariableName_2 == false);
                if (_equals_5) {
                  resource.addError("the name of a view variable should not end with \'@post\'", p, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
                }
                String _name_7 = p.getName();
                boolean _isDuplicateViewVariable = this.isDuplicateViewVariable(_name_7);
                if (_isDuplicateViewVariable) {
                  resource.addError("the view variable has been declared in a conflict context", p, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
                } else {
                  String _name_8 = ((Parameter) p).getName();
                  this.addViewVariableName(_name_8);
                }
              }
            }
          }
        }
        EList<VariableDeclaration> _variableDeclarations = ((ModelRule) root).getVariableDeclarations();
        for (final VariableDeclaration vd : _variableDeclarations) {
          {
            String _name_9 = vd.getName();
            boolean _isValidNonUpdatedSourceVariableName_3 = AnalysisUtil.isValidNonUpdatedSourceVariableName(_name_9);
            boolean _equals_6 = (_isValidNonUpdatedSourceVariableName_3 == false);
            if (_equals_6) {
              resource.addError("the name of a normal variable should not end with \'@post\'", vd, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
            }
            String _name_10 = vd.getName();
            boolean _isDuplicateNormalVariable_1 = this.isDuplicateNormalVariable(_name_10);
            if (_isDuplicateNormalVariable_1) {
              resource.addError("the normal variable has been declared in a conflict context", vd, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
            } else {
              String _name_11 = vd.getName();
              this.addNormalVariableName(_name_11);
            }
          }
        }
        EList<EObject> _eContents = ((ModelRule)root).eContents();
        for (final EObject o : _eContents) {
          this.collectVariableNames(o, resource);
        }
      } else {
        if ((root instanceof ArithmeticRule)) {
          EList<Parameter> _parameters_1 = ((ArithmeticRule) root).getParameters();
          for (final Parameter p_1 : _parameters_1) {
            DomainTag _tag_3 = ((Parameter) p_1).getTag();
            boolean _equals_6 = Objects.equal(_tag_3, DomainTag.NORMAL);
            if (_equals_6) {
              String _name_9 = p_1.getName();
              boolean _isValidNonUpdatedSourceVariableName_3 = AnalysisUtil.isValidNonUpdatedSourceVariableName(_name_9);
              boolean _equals_7 = (_isValidNonUpdatedSourceVariableName_3 == false);
              if (_equals_7) {
                resource.addError("the name of a normal variable should not end with \'@post\'", p_1, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
              }
              String _name_10 = p_1.getName();
              boolean _isDuplicateNormalVariable_1 = this.isDuplicateNormalVariable(_name_10);
              if (_isDuplicateNormalVariable_1) {
                resource.addError("the normal variable has been declared in a conflict context", p_1, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
              } else {
                String _name_11 = ((Parameter) p_1).getName();
                this.addNormalVariableName(_name_11);
              }
            } else {
              DomainTag _tag_4 = ((Parameter) p_1).getTag();
              boolean _equals_8 = Objects.equal(_tag_4, DomainTag.SOURCE);
              if (_equals_8) {
                String _name_12 = p_1.getName();
                boolean _isValidNonUpdatedSourceVariableName_4 = AnalysisUtil.isValidNonUpdatedSourceVariableName(_name_12);
                boolean _equals_9 = (_isValidNonUpdatedSourceVariableName_4 == false);
                if (_equals_9) {
                  resource.addError("the name of a source variable should not end with \'@post\'", p_1, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
                }
                String _name_13 = p_1.getName();
                boolean _isDuplicateSourceVariable_1 = this.isDuplicateSourceVariable(_name_13);
                if (_isDuplicateSourceVariable_1) {
                  resource.addError("the source variable has been declared in a conflict context", p_1, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
                } else {
                  String _name_14 = ((Parameter) p_1).getName();
                  this.addSourceVariableName(_name_14);
                }
              } else {
                DomainTag _tag_5 = ((Parameter) p_1).getTag();
                boolean _equals_10 = Objects.equal(_tag_5, DomainTag.VIEW);
                if (_equals_10) {
                  String _name_15 = p_1.getName();
                  boolean _isValidNonUpdatedSourceVariableName_5 = AnalysisUtil.isValidNonUpdatedSourceVariableName(_name_15);
                  boolean _equals_11 = (_isValidNonUpdatedSourceVariableName_5 == false);
                  if (_equals_11) {
                    resource.addError("the name of a view variable should not end with \'@post\'", p_1, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
                  }
                  String _name_16 = p_1.getName();
                  boolean _isDuplicateViewVariable_1 = this.isDuplicateViewVariable(_name_16);
                  if (_isDuplicateViewVariable_1) {
                    resource.addError("the view variable has been declared in a conflict context", p_1, Xmu2Package.Literals.NAMED_ELEMENT__NAME);
                  } else {
                    String _name_17 = ((Parameter) p_1).getName();
                    this.addViewVariableName(_name_17);
                  }
                }
              }
            }
          }
          EList<EObject> _eContents_1 = ((ArithmeticRule)root).eContents();
          for (final EObject o_1 : _eContents_1) {
            this.collectVariableNames(o_1, resource);
          }
        } else {
          if ((root instanceof UpdateStatement)) {
            Pattern source = ((UpdateStatement) root).getSource();
            this.collectVariablesInPattern(source, DomainTag.SOURCE, resource);
            this.checkVariableUsage(source, resource, DomainTag.SOURCE);
            Pattern view = ((UpdateStatement) root).getView();
            this.collectVariablesInPattern(view, DomainTag.VIEW, resource);
            this.checkVariableUsage(view, resource, DomainTag.VIEW);
            EList<UpdateClause> _clauses = ((UpdateStatement) root).getClauses();
            for (final UpdateClause uc : _clauses) {
              this.collectVariableNames(uc, resource);
            }
          } else {
            if ((root instanceof SwitchStatement)) {
              DomainTag flag = null;
              VariableExpression _root = ((SwitchStatement) root).getRoot();
              String _variable = _root.getVariable();
              boolean _existInSourceVariable = this.existInSourceVariable(_variable);
              if (_existInSourceVariable) {
                flag = DomainTag.SOURCE;
              } else {
                VariableExpression _root_1 = ((SwitchStatement) root).getRoot();
                String _variable_1 = _root_1.getVariable();
                boolean _existInViewVariable = this.existInViewVariable(_variable_1);
                if (_existInViewVariable) {
                  flag = DomainTag.VIEW;
                } else {
                  VariableExpression _root_2 = ((SwitchStatement) root).getRoot();
                  String _variable_2 = _root_2.getVariable();
                  boolean _existInNormalVariable = this.existInNormalVariable(_variable_2);
                  if (_existInNormalVariable) {
                    flag = DomainTag.NORMAL;
                  } else {
                    resource.addError("the root variable has not been declared or is declared in the updated-source domain", root, StatementPackage.Literals.SWITCH_STATEMENT__ROOT);
                  }
                }
              }
              EList<CaseClause> _cases = ((SwitchStatement) root).getCases();
              for (final CaseClause cc : _cases) {
                {
                  if ((cc instanceof PatternCaseClause)) {
                    boolean _equals_12 = Objects.equal(flag, DomainTag.NORMAL);
                    if (_equals_12) {
                      Pattern _condition = ((PatternCaseClause) cc).getCondition();
                      TreeIterator<EObject> rp = _condition.eAllContents();
                      while (rp.hasNext()) {
                        {
                          EObject o_2 = rp.next();
                          if ((o_2 instanceof VariableDeclaration)) {
                            String name = ((VariableDeclaration) o_2).getName();
                            if (((this.existInSourceVariable(name) || this.existInUpdatedSourceVariable(name)) || this.existInUpdatedSourceVariable(name))) {
                              EObject _eContainer = ((VariableDeclaration)o_2).eContainer();
                              EReference _eContainmentFeature = ((VariableDeclaration)o_2).eContainmentFeature();
                              resource.addError("the normal variable has been declared in a conflict context", _eContainer, _eContainmentFeature);
                            } else {
                              boolean _existInNormalVariable_1 = this.existInNormalVariable(name);
                              boolean _not = (!_existInNormalVariable_1);
                              if (_not) {
                                EObject _eContainer_1 = ((VariableDeclaration)o_2).eContainer();
                                EReference _eContainmentFeature_1 = ((VariableDeclaration)o_2).eContainmentFeature();
                                resource.addWarning("it is recommended to declare the normal variable", _eContainer_1, _eContainmentFeature_1);
                              }
                            }
                          }
                        }
                      }
                    } else {
                      Pattern _condition_1 = ((PatternCaseClause) cc).getCondition();
                      this.collectVariablesInPattern(_condition_1, flag, resource);
                    }
                    Pattern _condition_2 = ((PatternCaseClause) cc).getCondition();
                    this.checkVariableUsage(_condition_2, resource, flag);
                  } else {
                    if ((cc instanceof ExpressionCaseClause)) {
                      Expression _condition_3 = ((ExpressionCaseClause) cc).getCondition();
                      this.checkVariableUsage(_condition_3, resource, flag);
                    }
                  }
                  Statement _action = cc.getAction();
                  this.collectVariableNames(_action, resource);
                }
              }
            } else {
              if ((root instanceof EnforcePatternStatement)) {
                Pattern _pattern = ((EnforcePatternStatement) root).getPattern();
                this.collectVariablesInPattern(_pattern, DomainTag.UPDATED_SOURCE, resource);
                this.checkVariableUsage(root, resource, DomainTag.UPDATED_SOURCE);
              } else {
                if ((root instanceof DeleteNodeStatement)) {
                  VariableExpression _node = ((DeleteNodeStatement) root).getNode();
                  String varName = _node.getVariable();
                  boolean _isDuplicateUpdatedSourceVariable = this.isDuplicateUpdatedSourceVariable(varName);
                  if (_isDuplicateUpdatedSourceVariable) {
                    resource.addError("the updated source variable has been declared in a conflict context", root, StatementPackage.Literals.DELETE_NODE_STATEMENT__NODE);
                  } else {
                    this.addUpdatedSourceVariableName(varName);
                  }
                } else {
                  if ((root instanceof DeleteLinkStatement)) {
                    VariableExpression _source = ((DeleteLinkStatement) root).getSource();
                    String varName_1 = _source.getVariable();
                    boolean _isDuplicateUpdatedSourceVariable_1 = this.isDuplicateUpdatedSourceVariable(varName_1);
                    if (_isDuplicateUpdatedSourceVariable_1) {
                      resource.addError("the updated source variable has been declared in a conflict context", root, StatementPackage.Literals.DELETE_LINK_STATEMENT__SOURCE);
                    } else {
                      this.addUpdatedSourceVariableName(varName_1);
                    }
                    Expression _target = ((DeleteLinkStatement) root).getTarget();
                    this.checkVariableUsage(_target, resource, DomainTag.UPDATED_SOURCE);
                  } else {
                    if ((root instanceof LoopPath)) {
                      VariableDeclaration _variable_3 = ((LoopPath) root).getVariable();
                      String varName_2 = _variable_3.getName();
                      boolean _isDuplicateNormalVariable_2 = this.isDuplicateNormalVariable(varName_2);
                      if (_isDuplicateNormalVariable_2) {
                        resource.addError("the iterator variable has been declared", root, ExpressionPackage.Literals.LOOP_PATH__VARIABLE);
                      }
                    } else {
                      if ((root instanceof AssignStatement)) {
                        VariableExpression _updatedVariable = ((AssignStatement) root).getUpdatedVariable();
                        String varName_3 = _updatedVariable.getVariable();
                        boolean _isDuplicateUpdatedSourceVariable_2 = this.isDuplicateUpdatedSourceVariable(varName_3);
                        if (_isDuplicateUpdatedSourceVariable_2) {
                          resource.addError("the updated source variable has been declared in a conflict context", root, StatementPackage.Literals.ASSIGN_STATEMENT__UPDATED_VARIABLE);
                        } else {
                          this.addUpdatedSourceVariableName(varName_3);
                        }
                        Expression _value = ((AssignStatement) root).getValue();
                        this.checkVariableUsage(_value, resource, DomainTag.NORMAL);
                      } else {
                        if ((root instanceof ForEachStatement)) {
                          Pattern source_1 = ((ForEachStatement) root).getPattern();
                          PatternNode _root_3 = source_1.getRoot();
                          VariableDeclaration _variable_4 = _root_3.getVariable();
                          String name = _variable_4.getName();
                          boolean _existInSourceVariable_1 = this.existInSourceVariable(name);
                          if (_existInSourceVariable_1) {
                            this.collectVariablesInPattern(source_1, DomainTag.SOURCE, resource);
                          } else {
                            boolean _existInNormalVariable_1 = this.existInNormalVariable(name);
                            if (_existInNormalVariable_1) {
                              this.collectVariablesInPattern(source_1, DomainTag.NORMAL, resource);
                            }
                          }
                          EList<EObject> _eContents_2 = ((ForEachStatement)root).eContents();
                          for (final EObject o_2 : _eContents_2) {
                            this.collectVariableNames(o_2, resource);
                          }
                        } else {
                          if ((root instanceof Fail)) {
                            Expression _expression = ((Fail) root).getExpression();
                            this.checkVariableUsage(_expression, resource, DomainTag.NORMAL);
                          } else {
                            EList<EObject> _eContents_3 = root.eContents();
                            for (final EObject o_3 : _eContents_3) {
                              this.collectVariableNames(o_3, resource);
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    } catch (final Throwable _t) {
      if (_t instanceof Exception) {
        final Exception e = (Exception)_t;
        EObject _eContainer = root.eContainer();
        EReference _eContainmentFeature = root.eContainmentFeature();
        resource.addWarning("validity check is not finished because of some exceptions", _eContainer, _eContainmentFeature);
      } else {
        throw Exceptions.sneakyThrow(_t);
      }
    }
  }
}
