/*
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl

import edu.ustb.sei.mde.bxcore.dsl.scoping.BXCoreLinkingService

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class BXCoreRuntimeModule extends AbstractBXCoreRuntimeModule {
	
	override bindILinkingService() {
		BXCoreLinkingService
	}
	
}
