<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="bxmorel" nsURI="http://www.ustb.edu.cn/sei/mde/bxmorel" nsPrefix="bxmorel">
  <eClassifiers xsi:type="ecore:EClass" name="BXStatement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BXStatementBlock" eSuperTypes="#//BXStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" upperBound="-1"
        eType="#//BXStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXUpdate" eSuperTypes="#//BXStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//BXPattern" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="view" lowerBound="1" eType="#//BXPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statements" lowerBound="1"
        upperBound="3" eType="#//BXVStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXCase" eSuperTypes="#//BXStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" lowerBound="1" eType="#//StmtTag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="ecore:EClass ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cases" upperBound="-1"
        eType="#//BXCaseBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXCaseBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//BXPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" lowerBound="1"
        eType="#//BXStatement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXPattern" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BXTreePattern" eSuperTypes="#//BXPattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" lowerBound="1" eType="#//BXTemplateNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXUpdateMapping">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sVar" lowerBound="1" eType="ecore:EClass ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//ObjectVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tVar" lowerBound="1" eType="ecore:EClass ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//ObjectVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXTemplateNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//BXTemplateExp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="host" lowerBound="1" eType="ecore:EClass ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//ObjectVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXTemplateExp" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStructuralFeature"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXTemplateNestedNode" eSuperTypes="#//BXTemplateExp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="node" lowerBound="1" eType="#//BXTemplateNode"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXTemplateRelationalExpr" eSuperTypes="#//BXTemplateExp">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" lowerBound="1"
        eType="ecore:EEnum ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//AdditiveOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightValue" lowerBound="1"
        eType="ecore:EClass ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//AdditiveExp"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXVStatement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" upperBound="-1"
        eType="#//BXStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flag" lowerBound="1" eType="#//VStmtFlag"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VStmtFlag">
    <eLiterals name="match"/>
    <eLiterals name="unmatchv" value="1"/>
    <eLiterals name="unmatchs" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StmtTag">
    <eLiterals name="source"/>
    <eLiterals name="view" value="1"/>
    <eLiterals name="normal" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" lowerBound="1"
        eType="#//BXStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nVars" upperBound="-1"
        eType="ecore:EClass ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//PrimitiveVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sVars" upperBound="-1"
        eType="ecore:EClass ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//ObjectVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vVars" upperBound="-1"
        eType="ecore:EClass ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//ObjectVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spVars" upperBound="-1"
        eType="ecore:EClass ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//ObjectVariable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//BXParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BXParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" lowerBound="1" eType="#//VarTag"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="ecore:EClass ../../edu.ustb.sei.mde.morel/metamodel/morel.ecore#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="VarTag">
    <eLiterals name="source"/>
    <eLiterals name="view" value="1"/>
    <eLiterals name="context" value="2"/>
  </eClassifiers>
</ecore:EPackage>
