/**
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl.ide;

import edu.ustb.sei.mde.bxcore.dsl.ide.AbstractBXCoreIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class BXCoreIdeModule extends AbstractBXCoreIdeModule {
}
