/**
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import edu.ustb.sei.mde.bxcore.dsl.BXCoreRuntimeModule;
import edu.ustb.sei.mde.bxcore.dsl.BXCoreStandaloneSetup;
import edu.ustb.sei.mde.bxcore.dsl.ide.BXCoreIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class BXCoreIdeSetup extends BXCoreStandaloneSetup {
  @Override
  public Injector createInjector() {
    BXCoreRuntimeModule _bXCoreRuntimeModule = new BXCoreRuntimeModule();
    BXCoreIdeModule _bXCoreIdeModule = new BXCoreIdeModule();
    return Guice.createInjector(Modules2.mixin(_bXCoreRuntimeModule, _bXCoreIdeModule));
  }
}
