/**
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Type Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getContextTypeRef()
 * @model
 * @generated
 */
public interface ContextTypeRef extends EObject
{
} // ContextTypeRef
