/**
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.TypeDefinition#getTypeVars <em>Type Vars</em>}</li>
 * </ul>
 *
 * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getTypeDefinition()
 * @model
 * @generated
 */
public interface TypeDefinition extends Definition, ContextType
{
  /**
   * Returns the value of the '<em><b>Type Vars</b></em>' containment reference list.
   * The list contents are of type {@link edu.ustb.sei.mde.bxcore.dsl.bXCore.TypeVar}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Vars</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Vars</em>' containment reference list.
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getTypeDefinition_TypeVars()
   * @model containment="true"
   * @generated
   */
  EList<TypeVar> getTypeVars();

} // TypeDefinition
