/**
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Xmu Core Derive Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreDeriveSource#getDerivationFunctions <em>Derivation Functions</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreDeriveSource#getDerivedType <em>Derived Type</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreDeriveSource#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreDeriveSource()
 * @model
 * @generated
 */
public interface XmuCoreDeriveSource extends XmuCoreCompositionChildStatement
{
  /**
   * Returns the value of the '<em><b>Derivation Functions</b></em>' containment reference list.
   * The list contents are of type {@link edu.ustb.sei.mde.bxcore.dsl.bXCore.ContextAwareDerivationAction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Derivation Functions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Derivation Functions</em>' containment reference list.
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreDeriveSource_DerivationFunctions()
   * @model containment="true"
   * @generated
   */
  EList<ContextAwareDerivationAction> getDerivationFunctions();

  /**
   * Returns the value of the '<em><b>Derived Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Derived Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Derived Type</em>' containment reference.
   * @see #setDerivedType(OrderedTupleTypeLiteral)
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreDeriveSource_DerivedType()
   * @model containment="true"
   * @generated
   */
  OrderedTupleTypeLiteral getDerivedType();

  /**
   * Sets the value of the '{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreDeriveSource#getDerivedType <em>Derived Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Derived Type</em>' containment reference.
   * @see #getDerivedType()
   * @generated
   */
  void setDerivedType(OrderedTupleTypeLiteral value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(XmuCoreStatement)
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreDeriveSource_Body()
   * @model containment="true"
   * @generated
   */
  XmuCoreStatement getBody();

  /**
   * Sets the value of the '{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreDeriveSource#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(XmuCoreStatement value);

} // XmuCoreDeriveSource
