/**
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Xmu Core Fork</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreFork#getForks <em>Forks</em>}</li>
 * </ul>
 *
 * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreFork()
 * @model
 * @generated
 */
public interface XmuCoreFork extends XmuCoreStatement
{
  /**
   * Returns the value of the '<em><b>Forks</b></em>' containment reference list.
   * The list contents are of type {@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreForkBranch}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Forks</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Forks</em>' containment reference list.
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreFork_Forks()
   * @model containment="true"
   * @generated
   */
  EList<XmuCoreForkBranch> getForks();

} // XmuCoreFork
