/**
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Xmu Core Composition Child Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreCompositionChildStatement()
 * @model
 * @generated
 */
public interface XmuCoreCompositionChildStatement extends XmuCoreStatement
{
} // XmuCoreCompositionChildStatement
