/**
 * generated by Xtext 2.14.0
 */
package edu.ustb.sei.mde.bxcore.dsl.bXCore;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Xmu Core Context Source</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreContextSource#getMappingSource <em>Mapping Source</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreContextSource#getMappingView <em>Mapping View</em>}</li>
 *   <li>{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreContextSource#getBody <em>Body</em>}</li>
 * </ul>
 *
 * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreContextSource()
 * @model
 * @generated
 */
public interface XmuCoreContextSource extends XmuCoreCompositionChildStatement
{
  /**
   * Returns the value of the '<em><b>Mapping Source</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mapping Source</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapping Source</em>' containment reference.
   * @see #setMappingSource(OrderedTupleTypeLiteral)
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreContextSource_MappingSource()
   * @model containment="true"
   * @generated
   */
  OrderedTupleTypeLiteral getMappingSource();

  /**
   * Sets the value of the '{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreContextSource#getMappingSource <em>Mapping Source</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mapping Source</em>' containment reference.
   * @see #getMappingSource()
   * @generated
   */
  void setMappingSource(OrderedTupleTypeLiteral value);

  /**
   * Returns the value of the '<em><b>Mapping View</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mapping View</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapping View</em>' containment reference.
   * @see #setMappingView(OrderedTupleTypeLiteral)
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreContextSource_MappingView()
   * @model containment="true"
   * @generated
   */
  OrderedTupleTypeLiteral getMappingView();

  /**
   * Sets the value of the '{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreContextSource#getMappingView <em>Mapping View</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mapping View</em>' containment reference.
   * @see #getMappingView()
   * @generated
   */
  void setMappingView(OrderedTupleTypeLiteral value);

  /**
   * Returns the value of the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Body</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Body</em>' containment reference.
   * @see #setBody(XmuCoreStatement)
   * @see edu.ustb.sei.mde.bxcore.dsl.bXCore.BXCorePackage#getXmuCoreContextSource_Body()
   * @model containment="true"
   * @generated
   */
  XmuCoreStatement getBody();

  /**
   * Sets the value of the '{@link edu.ustb.sei.mde.bxcore.dsl.bXCore.XmuCoreContextSource#getBody <em>Body</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Body</em>' containment reference.
   * @see #getBody()
   * @generated
   */
  void setBody(XmuCoreStatement value);

} // XmuCoreContextSource
