/**
 * generated by Xtext 2.10.0
 */
package edu.ustb.sei.mde.xmuxtext.ui.contentassist;

import edu.ustb.sei.mde.xmuxtext.ui.contentassist.AbstractXmu2ProposalProvider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Xmu2ProposalProvider extends AbstractXmu2ProposalProvider {
  @Override
  public void complete_EntryPoint(final EObject model, final RuleCall ruleCall, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method accept(Object) is undefined for the type ICompletionProposalAcceptor"
      + "\nThe method createCompletionProposal(String, ContentAssistContext) is undefined");
  }
  
  @Override
  public void complete_ModelRule(final EObject model, final RuleCall ruleCall, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method accept(Object) is undefined for the type ICompletionProposalAcceptor"
      + "\nThe method createCompletionProposal(String, ContentAssistContext) is undefined");
  }
  
  @Override
  public void complete_UpdateStatement(final EObject model, final RuleCall ruleCall, final ContentAssistContext context, final ICompletionProposalAcceptor acceptor) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method accept(Object) is undefined for the type ICompletionProposalAcceptor"
      + "\nThe method createCompletionProposal(String, ContentAssistContext) is undefined");
  }
}
